In [34]:
import json
import pandas as pd


data_path = "/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/runs/sglang_comm_2ms"

# data = []
# with open(f"{data_path}/debug.jsonl","r") as f:
#     for line in f:
#         data.append(json.loads(line))

results = pd.read_csv(f"{data_path}/results.csv",sep="|")

In [35]:
results.keys()

Index(['request_id', 'subject', 'target_node', 'ingress_node', 'processed_by',
       'routed_from', 'routed_to', 'prefix_match_input_tokens',
       'expected_cache_hit_tokens', 'expected_cache_hit_ratio',
       'sglang_prompt_tokens', 'sglang_cache_hit_tokens',
       'sglang_uncached_prefill_tokens', 'sglang_cache_hit_ratio',
       'inference_time_s', 'actual_sglang_inference_time_s',
       'communication_time_s', 'routing_processing_time_s',
       'local_processing_time_s', 'other_processing_time_s',
       'local_snapshot_match_after_process', 'total_time_s', 'generated_text',
       'error'],
      dtype='str')

In [36]:
(results["communication_time_s"][:4500].sum())/4500

np.float64(0.0029556444444444442)

In [31]:
(results["actual_sglang_inference_time_s"][:4500].sum())/4500

np.float64(0.5304449777777778)

In [22]:
(results["total_time_s"][:4500].sum())/4500

np.float64(3.226129577777778)

In [19]:
(results["inference_time_s"][:4500].sum())/4500

np.float64(0.03587015555555556)

In [11]:
(results["inference_time_s"][:4500].sum() + results["communication_time_s"][:4500].sum())/4500

np.float64(0.0388258)

In [12]:
results["sglang_cache_hit_ratio"][:4500].sum()/4500

np.float64(0.8351608666666667)

In [23]:
import json
import pandas as pd


data_path = "/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/runs/sglang_comm_2ms_noroute"

# data = []
# with open(f"{data_path}/debug.jsonl","r") as f:
#     for line in f:
#         data.append(json.loads(line))

results = pd.read_csv(f"{data_path}/results.csv",sep="|")

In [24]:
results

,request_id,subject,target_node,ingress_node,processed_by,routed_from,routed_to,prefix_match_input_tokens,expected_cache_hit_tokens,expected_cache_hit_ratio,...,inference_time_s,actual_sglang_inference_time_s,communication_time_s,routing_processing_time_s,local_processing_time_s,other_processing_time_s,local_snapshot_match_after_process,total_time_s,generated_text,error
0,0,professional_law,0,0,0,NaN,NaN,1359,0,0.0000,...,0.0463,0.0208,0.0,0.0305,0.0097,0.0402,1359,0.0865,B,NaN
1,1,professional_psychology,1,1,1,NaN,NaN,460,0,0.0000,...,0.0388,0.0147,0.0,0.0073,0.0055,0.0128,460,0.0516,C,NaN
2,2,miscellaneous,2,2,2,NaN,NaN,292,0,0.0000,...,0.0374,0.0133,0.0,0.0066,0.0049,0.0115,292,0.0489,B,NaN
3,3,human_aging,3,3,3,NaN,NaN,351,1,0.0028,...,0.0379,0.0150,0.0,0.0069,0.0057,0.0126,351,0.0505,D,NaN
4,4,anatomy,0,0,0,NaN,NaN,388,0,0.0000,...,0.0382,0.0212,0.0,0.0130,0.0164,0.0294,388,0.0676,B,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5985,5985,high_school_biology,0,0,0,NaN,NaN,485,0,0.0000,...,0.0363,1.0903,0.0,3.4800,3.2868,6.7668,0,6.8031,D,NaN
5986,5986,moral_scenarios,1,1,1,NaN,NaN,613,561,0.9152,...,0.0354,2.2090,0.0,1.7050,2.2287,3.9337,613,3.9691,A,NaN
5987,5987,world_religions,2,2,2,NaN,NaN,244,0,0.0000,...,0.0353,1.2266,0.0,4.0822,3.7954,7.8776,0,7.9129,C,NaN
5988,5988,security_studies,3,3,3,NaN,NaN,917,795,0.8670,...,0.0360,2.9073,0.0,2.2201,1.2748,3.4949,917,3.5309,B,NaN
5989,5989,moral_disputes,0,0,0,NaN,NaN,385,0,0.0000,...,0.0356,1.2706,0.0,4.3849,3.6281,8.0130,0,8.0486,A,NaN

In [25]:
(results["total_time_s"][:4500].sum())/4500

np.float64(3.518403644444444)

In [15]:
(results["inference_time_s"][:4500].sum() + results["communication_time_s"][:4500].sum())/4500

np.float64(0.036033199999999994)

In [16]:
results["sglang_cache_hit_ratio"][:4500].sum()/4500

np.float64(0.8023312666666667)

In [49]:
results = results[:8000]

In [50]:
print(results['total_time_s'].sum()/len(results), results['sglang_cache_hit_ratio'].sum()/len(results))

0.7788269124999999 0.8209753499999999

In [32]:
import json
import pandas as pd


data_path = "/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/runs/comm_2ms_gpu0.1_n4"

# data = []
# with open(f"{data_path}/debug.jsonl","r") as f:
#     for line in f:
#         data.append(json.loads(line))

results = pd.read_csv(f"{data_path}/results.csv",sep="|")

In [27]:
results["sglang_cache_hit_ratio"][:4500].sum()/4500

np.float64(0.8347788222222222)

In [28]:
(results["total_time_s"][:4500].sum())/4500

np.float64(0.6134635111111111)

In [54]:
print(results['total_time_s'].sum()/len(results), results['sglang_cache_hit_ratio'].sum()/len(results))

0.8494476 0.841299075

In [55]:
results

,request_id,subject,target_node,ingress_node,processed_by,routed_from,routed_to,prefix_match_input_tokens,expected_cache_hit_tokens,expected_cache_hit_ratio,sglang_prompt_tokens,sglang_cache_hit_tokens,sglang_cache_hit_ratio,local_snapshot_match_after_process,total_time_s,generated_text,error
0,0,professional_law,0,0,0,NaN,NaN,1359,0,0.0000,1359,0,0.0000,1359,0.0140,B,NaN
1,1,professional_psychology,1,1,1,NaN,NaN,460,0,0.0000,460,0,0.0000,460,0.0102,C,NaN
2,2,miscellaneous,2,2,2,NaN,NaN,292,0,0.0000,292,0,0.0000,292,0.0194,B,NaN
3,3,human_aging,3,3,3,NaN,NaN,351,1,0.0028,351,1,0.0028,351,0.0127,D,NaN
4,4,anatomy,0,0,0,NaN,NaN,388,0,0.0000,388,0,0.0000,388,0.0111,B,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7995,professional_medicine,2,2,0,2.0,0.0,1222,1100,0.9002,1222,1100,0.9002,1222,0.1559,B,NaN
7996,7996,miscellaneous,3,3,2,3.0,2.0,402,261,0.6493,402,261,0.6493,261,1.5642,C,NaN
7997,7997,conceptual_physics,0,0,0,NaN,NaN,281,244,0.8683,281,244,0.8683,281,2.1029,D,NaN
7998,7998,college_medicine,1,1,0,1.0,0.0,586,447,0.7628,586,447,0.7628,586,1.6975,D,NaN
7999,7999,elementary_mathematics,2,2,2,NaN,NaN,484,0,0.0000,484,320,0.6612,0,1.1616,B,NaN

In [10]:
results_h = results[results["subject"]=="high_school_statistics"]

In [12]:
results_h[results_h['total_time_s'] > 0.7]

,request_id,subject,target_node,ingress_node,processed_by,routed_from,routed_to,prefix_match_input_tokens,expected_cache_hit_tokens,expected_cache_hit_ratio,sglang_prompt_tokens,sglang_cache_hit_tokens,sglang_cache_hit_ratio,local_snapshot_match_after_process,total_time_s,generated_text,error
764,764,high_school_statistics,3,3,3,NaN,NaN,709.0,569.0,0.8025,709.0,569.0,0.8025,709.0,0.7252,C,NaN
1709,1709,high_school_statistics,0,0,3,0.0,3.0,738.0,569.0,0.7710,738.0,569.0,0.7710,738.0,0.7811,B,NaN
2163,2163,high_school_statistics,2,2,3,2.0,3.0,668.0,569.0,0.8518,668.0,569.0,0.8518,668.0,1.2158,B,NaN
2174,2174,high_school_statistics,1,1,3,1.0,3.0,702.0,568.0,0.8091,702.0,568.0,0.8091,702.0,1.1454,C,NaN
2295,2295,high_school_statistics,2,2,3,2.0,3.0,746.0,569.0,0.7627,746.0,569.0,0.7627,746.0,1.2953,C,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13635,13635,high_school_statistics,2,2,3,2.0,3.0,765.0,0.0,0.0000,765.0,569.0,0.7438,0.0,1.3225,B,NaN
13690,13690,high_school_statistics,1,1,3,1.0,3.0,706.0,0.0,0.0000,706.0,570.0,0.8074,0.0,3.8958,C,NaN
13703,13703,high_school_statistics,2,2,3,2.0,3.0,710.0,0.0,0.0000,710.0,569.0,0.8014,0.0,1.3153,A,NaN
13734,13734,high_school_statistics,1,1,3,1.0,3.0,695.0,0.0,0.0000,695.0,569.0,0.8187,0.0,0.9104,B,NaN
13754,13754,high_school_statistics,1,1,3,1.0,3.0,703.0,0.0,0.0000,703.0,577.0,0.8208,0.0,3.7816,C,NaN

In [13]:
data[13754]

{'request_id': 13754,
 'subject': 'high_school_statistics',
 'target_node': 1,
 'ingress_node': 1,
 'selected_node': 3,
 'processed_by': 3,
 'routed_from': 1,
 'routed_to': 3,
 'prefix_match_input_tokens': 703,
 'sglang_prompt_tokens': 703,
 'sglang_cache_hit_tokens': 577,
 'sglang_cache_hit_ratio': 0.8208,
 'per_node_expected_cache_hits': [{'node_id': 0,
   'expected_cache_hit_tokens': 1,
   'was_selected': False},
  {'node_id': 1, 'expected_cache_hit_tokens': 0, 'was_selected': False},
  {'node_id': 2, 'expected_cache_hit_tokens': 1, 'was_selected': False},
  {'node_id': 3, 'expected_cache_hit_tokens': 568, 'was_selected': True}],
 'local_snapshot_match_after_process': 0}

In [14]:
df = pd.read_csv("/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/datasets/requests.csv")

In [16]:
df = df[df['subject'] == "high_school_statistics"]

In [18]:
df.reset_index(inplace=True,drop=True)
df.to_csv("/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/datasets/requests_high_school_stats.csv")

In [19]:
df

,text,target_node,subject
0,The weight of an aspirin tablet is 300 milligr...,3,high_school_statistics
1,The weight of an aspirin tablet is 300 milligr...,3,high_school_statistics
2,The weight of an aspirin tablet is 300 milligr...,2,high_school_statistics
3,The weight of an aspirin tablet is 300 milligr...,3,high_school_statistics
4,The weight of an aspirin tablet is 300 milligr...,0,high_school_statistics
...,...,...,...
206,The weight of an aspirin tablet is 300 milligr...,2,high_school_statistics
207,The weight of an aspirin tablet is 300 milligr...,1,high_school_statistics
208,The weight of an aspirin tablet is 300 milligr...,2,high_school_statistics
209,The weight of an aspirin tablet is 300 milligr...,1,high_school_statistics
210,The weight of an aspirin tablet is 300 milligr...,1,high_school_statistics

In [39]:
import json
import pandas as pd


data_path = "/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/runs/sglang_run_20260429_064215"

data = []
with open(f"{data_path}/debug.jsonl","r") as f:
    for line in f:
        data.append(json.loads(line))

results = pd.read_csv(f"{data_path}/results.csv",sep="|")

In [40]:
results

,request_id,subject,target_node,ingress_node,processed_by,routed_from,routed_to,prefix_match_input_tokens,expected_cache_hit_tokens,expected_cache_hit_ratio,sglang_prompt_tokens,sglang_cache_hit_tokens,sglang_cache_hit_ratio,local_snapshot_match_after_process,total_time_s,generated_text,error
0,0,high_school_statistics,1,0,0,NaN,NaN,703,1,0.0014,703,1,0.0014,703,0.0121,C,NaN
1,1,high_school_statistics,1,0,0,NaN,NaN,695,568,0.8173,695,568,0.8173,695,0.0090,B,NaN
2,2,high_school_statistics,2,0,0,NaN,NaN,710,568,0.8000,710,568,0.8000,710,0.0087,A,NaN
3,3,high_school_statistics,1,0,0,NaN,NaN,706,577,0.8173,706,577,0.8173,706,0.0082,C,NaN
4,4,high_school_statistics,2,0,0,NaN,NaN,765,568,0.7425,765,568,0.7425,765,0.0087,B,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,206,high_school_statistics,0,0,0,NaN,NaN,728,571,0.7843,728,571,0.7843,728,0.3423,C,NaN
207,207,high_school_statistics,3,0,0,NaN,NaN,713,569,0.7980,713,569,0.7980,713,0.3419,B,NaN
208,208,high_school_statistics,2,0,0,NaN,NaN,690,571,0.8275,690,571,0.8275,690,0.1656,A,NaN
209,209,high_school_statistics,3,0,0,NaN,NaN,631,569,0.9017,631,569,0.9017,631,0.3453,C,NaN
210,210,high_school_statistics,3,0,0,NaN,NaN,697,570,0.8178,697,570,0.8178,697,0.3430,C,NaN

In [35]:
df = pd.read_csv("/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/datasets/requests_high_school_stats.csv")

In [36]:
df_reversed = df[::-1]

In [38]:
df_reversed.reset_index(inplace=True, drop=True)
df_reversed.to_csv("/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/datasets/requests_high_school_stats_reversed.csv")

In [29]:
text_0 = df['text'][0]

In [31]:
df['text'] = text_0
df.to_csv("/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/datasets/requests_high_school_stats_single_text.csv")

In [32]:
df

,Unnamed: 0,text,target_node,subject
0,0,The weight of an aspirin tablet is 300 milligr...,3,high_school_statistics
1,1,The weight of an aspirin tablet is 300 milligr...,3,high_school_statistics
2,2,The weight of an aspirin tablet is 300 milligr...,2,high_school_statistics
3,3,The weight of an aspirin tablet is 300 milligr...,3,high_school_statistics
4,4,The weight of an aspirin tablet is 300 milligr...,0,high_school_statistics
...,...,...,...,...
206,206,The weight of an aspirin tablet is 300 milligr...,2,high_school_statistics
207,207,The weight of an aspirin tablet is 300 milligr...,1,high_school_statistics
208,208,The weight of an aspirin tablet is 300 milligr...,2,high_school_statistics
209,209,The weight of an aspirin tablet is 300 milligr...,1,high_school_statistics
210,210,The weight of an aspirin tablet is 300 milligr...,1,high_school_statistics

In [5]:

from transformers import AutoTokenizer

model_name = "Qwen/Qwen2.5-0.5B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)

requests = pd.read_csv("/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/datasets/requests.csv")

/home/ssn899/miniforge3/envs/dist2/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [8]:
max_len = 0
min_len = 1000000000
for idx,ele in requests.iterrows():
    curr_len = len(tokenizer.encode(ele['text'], add_special_tokens=False))
    max_len = max(max_len,curr_len)
    min_len = min(min_len, curr_len)


print(max_len, min_len)

2180 234

In [2]:
import os
import yaml

for ele in os.listdir("/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/config"):
    if ele.endswith(".yaml") and ele.startswith("gpu0.05"):
        print(ele)
        with open(f"/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/config/{ele}","r") as f:
            data = yaml.safe_load(f)
        data["run"]["overwrite_existing"] = True
        data["sglang"]["mem_fraction_static"] = 0.1
        name = ele.replace("gpu0.05","gpu0.1")
        with open(f"/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/config/{name}","w") as f:
            yaml.dump(data,f)

gpu0.05_sglang_comm_1s.yaml
gpu0.05_sglang_comm_2ms_skewed.yaml
gpu0.05_sglang_comm_1s_noroute.yaml
gpu0.05_sglang_comm_2ms_poll0.1_noroute.yaml
gpu0.05_sglang_comm_2ms_poll0.02.yaml
gpu0.05_sglang_comm_2ms_skewed_noroute.yaml
gpu0.05_sglang_comm_2ms_poll0.02_noroute.yaml
gpu0.05_sglang_comm_2ms.yaml
gpu0.05_sglang_comm_2ms_poll2.yaml
gpu0.05_sglang_comm_200ms_noroute.yaml
gpu0.05_sglang_comm_2ms_noroute.yaml
gpu0.05_sglang_comm_2ms_poll0.1.yaml
gpu0.05_sglang_comm_2ms_poll2_noroute.yaml
gpu0.05_sglang_comm_200ms.yaml

In [2]:
import os
import yaml
import pandas as pd
import json

for ele in os.listdir("/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/runs"):
    results_path = os.path.join("/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/runs",ele,"results.csv")
    if ele.startswith("gpu0.1") and os.path.exists(results_path):
        df = pd.read_csv(results_path,sep="|")
        print(ele,len(df))

gpu0.1_sglang_comm_200ms 6461
gpu0.1_sglang_comm_2ms 6748
gpu0.1_sglang_comm_2ms_poll0.1_noroute 311
gpu0.1_sglang_comm_2ms_poll0.1 6515
gpu0.1_sglang_comm_1s_noroute 9224
gpu0.1_sglang_comm_2ms_noroute 7712
gpu0.1_sglang_comm_1s 7602
gpu0.1_sglang_comm_2ms_poll2 7338
gpu0.1_sglang_comm_200ms_noroute 8248

In [2]:
import os
import yaml
import pandas as pd
import json

total_configs = []

for ele in os.listdir("/home/ssn899/Desktop/Distributed-Inference-for-Edge-LLMs/config"):
    if ele.startswith("gpu0.1"):
        total_configs.append(ele[:-5])
        results_path = os.path.join("/home/ssn899/Desktop/Distributed-Inference-for-Edge-LLMs/runs",ele[:-5],"results.csv")
        if os.path.exists(results_path):
            df = pd.read_csv(results_path,sep="|")
            print("Present -", ele[:-5], len(df))
        else:
            print(ele[:-5])

Present - gpu0.1_sglang_comm_2ms_poll0.02_noroute 4456
Present - gpu0.1_sglang_comm_2ms_skewed_noroute 4549
Present - gpu0.1_sglang_comm_2ms_skewed 4479
Present - gpu0.1_sglang_comm_200ms_noroute 8702
Present - gpu0.1_sglang_comm_2ms_poll2 7679
Present - gpu0.1_sglang_comm_1s_noroute 9750
Present - gpu0.1_sglang_comm_2ms 7070
Present - gpu0.1_sglang_comm_2ms_noroute 8129
gpu0.1_sglang_comm_2ms_poll2_noroute
gpu0.1_sglang_comm_2ms_poll0.1_noroute
Present - gpu0.1_sglang_comm_1s 7980
Present - gpu0.1_sglang_comm_200ms 6753
Present - gpu0.1_sglang_comm_2ms_poll0.02 3600
Present - gpu0.1_sglang_comm_2ms_poll0.1 6848